### ISSUE TITLE
Замечания по коммитам

### ISSUE THREAD

**Issue by alexey-malov** [JakimychevNikolaj/ObjectOrientedProgramming#6]
В сообщениях коммита описывайте характер изменений.

Сообщение "update source files" ровным счетом ничего не говорит о том, что было сделано, потому как любой коммит связан с обновлением файлов.

Чтобы легче было придумать сообщение, делайте коммиты как можно чаще

Не надо писать "обновил файл "Имя файла"", информация о коммите без того содержит инфромацию о том, какие файлы были изменены, добавлены.

Описывайте, что именно в программе было изменено с данным коммитом. Примеры:
- Добавлено взаимодействие с пользователем
- Исправлена проблема с обработкой отрицательных чисел

**Comment by H4817** [comment]
Хорошо, понял. Исправлюсь.
